### ISSUE TITLE
Angular 14 update planned?

### ISSUE THREAD

**Issue by SolidOctoEnigma** [diprokon/ng-table-virtual-scroll#107]
Is Angular 14 update planned, in progress or there is not plan for it yet?

**Comment by diprokon** [comment]
@SolidOctoEnigma is there any issues to use this lib with angular 14/15? Does it require any update?

**Comment by Moik** [comment]
@diprokon After updating the app to Angular 15 we are getting the error `Cannot read properties of undefined (reading '_switchDataSource')`. Also `paginator` property in `TableVirtualScrollDataSource` has incompatible type with Material paginator

**Comment by diprokon** [comment]
Ok, thanks for reporting
I will check soon

**Comment by harry-kalligeros** [comment]
Any progress on this ?

**Comment by motabass** [comment]
I made a simple workaround by using #virtualScrollTable istead of the class name for referencing the mat-table. Maybe that helps?

https://github.com/diprokon/ng-table-virtual-scroll/pull/110

**Comment by diprokon** [comment]
After my investigation, there is no issues with Angular 15 or Angular Material 15. Everything works as before

On the other hand, there described issues presented, if "Legacy" table is used (MatLegacyTableModule). Fix for it will be in the next release (in couple days)

**Comment by TobiDimmel** [comment]
@diprokon Have your tried the example with sticky header? It doesn't work with the new MDC-based MatTable since the CSS-classes have changed.

I did a basic update process with the Angular CLI for the repository and added a fix for the sticky header problem (see [/TobiDimmel/ng-table-virtual-scroll/tree/angular-v15](/TobiDimmel/ng-table-virtual-scroll/tree/angular-v15)).
I can make a PR if you want.

One thought to `MatLegacyTableModule`: maybe a proper solution is to also provide a legacy module to align it with the Angular Material approach.

**Comment by danielfnz** [comment]
Any progress on this ?

**Comment by jb-oahmed** [comment]
I'm still seeing this issue with `TypeError: Cannot read properties of undefined (reading '_switchDataSource')
    at TableItemSizeDirective.ngAfterContentInit (ng-table-virtual-scroll.mjs:251:50)`.
I'm using Angular version 16 with the MatLegacyTableModule. Is there a planned fix?
