### ISSUE TITLE
Scrolling issue when using sticky column

### ISSUE THREAD

**Issue by dimmelsw** [diprokon/ng-table-virtual-scroll#126]
We still have scrolling issues with sticky columns similar to #58 and #60
It only occurse in Chrome and Edge Browser.
Firefox is fine.

It is reproducable in stackblitz https://stackblitz.com/edit/stackblitz-starters-du8hew  

While debugging we see 2 scroll events after scrolling down one tick with the mouse wheel.
The first event looks fine with moving the scrolloffset downwards, but the second events moves the scrolloffset up again.

**Comment by Borys91** [comment]
Also having this problem, but in my case I get even more than two events. I also tried in the example above to change the scroll when clicking on the button using scrollToOffset() and I also receive the event several times, but somewhere after the 2nd or 3rd click. Any suggestions on what I can do to fix the problem. Thanks.

**Comment by sychd** [comment]
Hello! We've faced same issue in our project and reproduced it on library's example page (gif is attached). Checked it in Chrome, Safari and Firefox - issue has not been reproduced in Safari only.

The issue is that table jumps one row back on each new row entered/left the viewport. 

![Screen Recording 2023-09-27 at 11 09 09](https://github.com/diprokon/ng-table-virtual-scroll/assets/9273187/1db9b7e8-f17d-4e82-9b9f-a093c94f3e2d)

**Comment by jwedel** [comment]
Same here. We have some very weird scrolling behaviour. It's a lot worse than what @sychd showed.

- If you drag down the scroll bar handle, it gets offset immediately. So it the scroll bar handle is like 20px above the mouse
- When you reach the bottom of 500 elemens, it start heavy flickering
- Also when using the mouse wheel, it shows heavy flickering.
- The flickering continues even when not doing anything until you further scroll down.

In FF, it works.

**Comment by diprokon** [comment]
@jwedel Hi

I'm still the maintainer. I've tried to fix this issue a few times without success.

You can try to find a solution and create a PR - I would greatly appreciate it.
